# Generated by Django 4.1.5 on 2023-05-05 09:40

from django.db import migrations, models
import performances.fields


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_alter_act_sound_sample_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='sound_sample_url',
        ),
        migrations.AddField(
            model_name='act',
            name='insta_url',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='act',
            name='sound_sample_urls',
            field=performances.fields.MultiURLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='act',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='act',
            name='genre',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
