# Generated by Django 4.1.5 on 2023-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_remove_act_corresponding_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/acts/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img/workshops/'),
        ),
    ]
