# Generated by Django 4.1.5 on 2023-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0004_alter_act_corresponding_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='name',
            new_name='stage_name',
        ),
    ]
