# Generated by Django 4.1.5 on 2023-05-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0005_rename_name_act_stage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='corresponding_users',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='corresponding_users',
        ),
        migrations.AddField(
            model_name='act',
            name='corresponding_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshop',
            name='corresponding_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(default=None, upload_to='static/img/workshops/'),
        ),
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.ImageField(upload_to='static/img/acts/'),
        ),
    ]
