# Generated by Django 4.1.5 on 2023-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_remove_act_corresponding_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='sound_sample_urls',
        ),
        migrations.AddField(
            model_name='act',
            name='sound_sample_url',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
