# Generated by Django 4.1.5 on 2023-02-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='bezahlt',
        ),
        migrations.AddField(
            model_name='user',
            name='bezahlt',
            field=models.BooleanField(default=False),
        ),
    ]
