# Generated by Django 4.1.5 on 2023-03-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_guest_bezahlt_user_bezahlt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefonnummer',
        ),
    ]
