# Generated by Django 4.1.5 on 2023-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_telefonnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nachname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='vorname',
            field=models.CharField(max_length=64),
        ),
    ]
